"""Default tuning parameters for the manual piano keyboard detector."""

DEFAULT_DETECTION_PARAMS = {
    "black_upper_ratio": 0.6,
    "black_bottom_ratio": 0.5,
    "black_threshold": 70,
    "black_threshold_method": "otsu",
    "black_adaptive_block_size": 31,
    "black_adaptive_c": 5,
    "black_column_ratio": 0.10,
    "black_min_width": 10,
    "black_max_width": 100,
    "white_bottom_ratio": 0.85,
    "white_edge_std_factor": 2.0,
    "white_min_width": 15,
    "white_initial_top_ratio": 0.8,
    "white_initial_height_ratio": 0.3,
    "edge_boundary_padding_px": 3,
    "padding_percent": 0.25,
    "trim_saturation_threshold": 45,
    "trim_gray_threshold": 140,
    "trim_row_height": 20,
    "white_strip_dark_threshold": 60,
    "white_strip_dark_fraction": 0.02,
    "white_strip_min_run": 8,
    "white_strip_allow_failures": 1,
    "white_edge_left_shift_ticks": 0,
    "white_edge_right_shift_ticks": 0,
    "white_sep_ratio": 0.55,
    "white_sep_dyn_min": 8,
    "white_sep_close_kernel": 5,
    "white_sep_open_kernel": 3,
    "white_sep_min_width": 1,
    "type_aware_assignment": True,
    "black_recovery_enabled": True,
    "black_recovery_ratio": 0.6,
    "black_recovery_column_ratio_scale": 0.6,
    "black_split_max_factor": 1.6,
}

__all__ = ["DEFAULT_DETECTION_PARAMS"]
